SELECT * FROM emp;

SELECT empno, ename, deptno FROM emp;

SELECT 
 SAL, 
 ENAME,
 123,
 '문자ENG123'
 FROM EMP;

SELECT deptno FROM emp;
--중복 데이터를 삭제하는 DISTINCT
SELECT DISTINCT deptno FROM emp;
SELECT DISTINCT job FROM emp;
-- 별칭을 지정할떈 하고싶은곳 뒤에 별칭으로 적기
SELECT ename, sal, sal*12+comm, comm FROM emp;
SELECT ename, sal, sal*12+comm AS annsal, comm FROM emp;
SELECT ename, sal, sal*12+comm , comm FROM emp;
SELECT ename AS name FROM emp;
--AS 한글 쓸땐 '' X 
--원하는 순서로 데이터를 정렬하는 ORDER BY 절 
--오름차순일떈 (낮은순) ASC 생략가능 , 내림차순일떈 DESC 생략불가능
SELECT * FROM emp 
ORDER BY sal ASC;
SELECT * FROM emp 
ORDER BY sal DESC;
SELECT * FROM emp 
ORDER BY deptno,sal,empno;
SELECT * FROM emp 
ORDER BY empno DESC;
SELECT * FROM emp 
ORDER BY deptno ASC ,sal DESC ,empno;
SELECT distinct job FROM emp;
SELECT 
empno AS employee_no,
ename AS employee_name 
FROM emp 
ORDER BY deptno DESC,ENAME;
--필요한 데이터를 출력할때 쓰는 WHERE 절
SELECT 
* FROM EMP 
WHERE DEPTNO = 30; 
--조건 연산자 AND와 OR AND는 모든조건을 만족 OR는 둘중 하나만 맞으면OK
SELECT 
* FROM  EMP
WHERE DEPTNO= 30
AND JOB = 'SALESMAN';
SELECT * FROM EMP 
WHERE EMPNO = 7499 AND DEPTNO =30;
SELECT * FROM EMP 
WHERE MGR =7839 AND DEPTNO =20;
SELECT * FROM emp
WHERE deptno = 30 OR job= 'CLERK';
-- 한줄 주석 
/*  AND= 논리곱 OR = 논리합 ( ) 를 잘 쓸것.
  범위주석 
 */   
SELECT * FROM EMP 
WHERE SAL >= 3000; 
SELECT * FROM EMP 
 WHERE SAL >= 2500 
 AND JOB= 'ANALYST';
SELECT * FROM EMP 
--WHERE SAL != 3000;
WHERE SAL <> 3000;

SELECT * FROM EMP 
WHERE NOT SAL <= 3000; 
--(3000이 아니지만 3000보다 높은것) 
문제1.급여가 1500이상 3000미만 사원 출력

SELECT * FROM EMP 
WHERE SAL >= 1500 AND SAL <3000;

문제2. JOB이 CLERK이거나 급여가 2000초과 이면서 부서번호 10번인 사원 출력
--JOB을 쓸떄는 ''를 쓰고 안에를 대문자로 쓸것.
SELECT * FROM EMP 
WHERE JOB='CLERK'OR (SAL >2000 AND DEPTNO =10);


문제3 DEPTNO가  10 또는 20인 모든사원

SELECT * FROM EMP 
WHERE DEPTNO =10 OR DEPTNO=20;

문제4. 부서번호가 20 또는 30인 사원중에서 급여가 2000~3000 사이(포함)인 사람의 연봉이 작은 순으로 출력
단, 연봉이 같은경우 이름이 빠른순으로 정렬하여 출력. 
 
SELECT * FROM EMP 
WHERE (DEPTNO =20 OR DEPTNO=30)
AND (SAL >=2000 AND SAL<= 3000)
ORDER BY SAL,ENAME;

SELECT * FROM EMP 
WHERE DEPTNO IN (10,20);
-- IN은 같은 칼럼끼리 묶을떄 쓴다
SELECT * FROM EMP
WHERE  (SAL BETWEEN 2000 AND 3000);
--BETWEEN에서의 AND는 AND와는 다른것.
--2000이상 3000이하
--BETWEEN은 미만, 초과는 표현할 수 없다
--2000 미만이거나 3000초과로 만들려면 () 앞에 NOT 붙이기.
SELECT * FROM EMP
WHERE  (SAL NOT BETWEEN 2000 AND 3000);

SELECT * FROM EMP 
WHERE  (SAL NOT BETWEEN 2000 AND 3000)
AND DEPTNO=30;

SELECT * FROM EMP 
WHERE DEPTNO IN (20,30) 
AND (SAL BETWEEN 2000 AND 3000)
ORDER BY SAL,ENAME;

--LIKE 연산자 _ 와 %  _은 몇글잔지 찾고싶을떄 
SELECT * FROM EMP 
WHERE ENAME LIKE 'S%';
--N으로 끝나는 이름
SELECT * FROM EMP
WHERE ENAME LIKE '%N';

SELECT * FROM EMP 
WHERE ENAME LIKE '_L%';
--이름이 다섯글자 인사람
SELECT * FROM EMP
WHERE ENAME LIKE '_____';

SELECT * FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT * FROM EMP 
WHERE ENAME NOT LIKE '%A%';

SELECT COMM FROM EMP;

SELECT * FROM EMP
WHERE COMM = NULL;

SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE COMM IS NOT NULL;

SELECT * FROM EMP 
WHERE MGR  IS NULL;

SELECT * FROM EMP 
WHERE MGR  IS NOT NULL;
 
--집합 연산자 UNION
SELECT * FROM EMP WHERE DEPTNO = 10
UNION
SELECT * FROM EMP WHERE DEPTNO = 20;

SELECT EMPNO,ENAME ,SAL ,DEPTNO FROM EMP WHERE DEPTNO =10
UNION
SELECT SAL, JOB, DEPTNO, SAL FROM EMP WHERE DEPTNO=20;
--UNION ALL 중복된 결괏값 모두 출력 UNION은 중복은 제거 하고 나옴.
SELECT EMPNO, ENAME , SAL ,DEPTNO
FROM EMP 
WHERE DEPTNO = 10
UNION 
SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP BONUS WHERE DEPTNO =10;

SELECT EMPNO, ENAME , SAL ,DEPTNO
FROM EMP 
WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP WHERE DEPTNO =10;
--1. emp 테이블을 사용하여 다음과 같이 사원이름이 s로 끝나는 사원 데이터를 모두 출력하는 sql 구문을 작성
SELECT *FROM emp WHERE ename LIKE'%S';
--2. EMP 테이블을 사용하여 30번 부서에서 근무하는 사원 중에 직책이 SALESMAN인 사원의 직책 ,급여 ,부서번호를 
--출력하는 SQL구문
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP WHERE DEPTNO=30 AND JOB='SALESMAN';
--문제3
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP 
WHERE DEPTNO IN (20,30) 
AND SAL>2000;
--집합연산자 사용한 방식
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP 
WHERE DEPTNO =20 AND SAL > 2000
UNION ALL
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO FROM EMP 
WHERE DEPTNO =30 AND SAL >2000;

--문제4
SELECT *FROM EMP 
WHERE NOT (SAL>=2000 AND SAL <=3000);
--문제 5
SELECT ENAME,EMPNO,SAL,DEPTNO FROM EMP 
WHERE ENAME LIKE '%E%' AND
(SAL NOT BETWEEN 1000 AND 2000) AND DEPTNO=30;
--문제 6 
SELECT * FROM EMP 
WHERE COMM IS NULL 
AND MGR IS NOT NULL
AND JOB IN('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%';